### ISSUE TITLE
部署之后打开是全白的

### ISSUE THREAD

**Issue by LCorleone** [Ares-Chang/wooden-fish#2]
<img width="1738" alt="image" src="https://github.com/Ares-Chang/wooden-fish/assets/22718985/f1ea5788-c3d0-4dd4-a91b-6e42d8f0f2f7">
如图所示

**Comment by Ares-Chang** [comment]
麻烦提供下运行环境及最小重现，[为什么需要最小重现](https://areschang.top/demo-repo).

你用的不会是 IE 吧？看图标应该是 css 样式没生效导致

**Comment by LCorleone** [comment]
其实我就是git clone之后按照步骤build的，一台破破的腾讯云的linux机器，chrome浏览器。
其实网页右上角的设置和声音按钮都是有的，就是看不出，我怀疑是背景颜色渲染的问题，木鱼敲击的功能也是ok的

**Comment by LCorleone** [comment]
白的部分右上角其实是能点击的，就是有设置和声音按钮的，我觉得是背景的颜色问题？很奇怪

**Comment by LCorleone** [comment]
敲击功能也都是ok的

**Comment by Ares-Chang** [comment]
请检查浏览器版本，如果可以升级为最新版本。

如果未解决问题，可以抛一个可访问链接出来，根据你现在反馈的信息我暂时无法确认问题，

唯一能确定的是我的 logo 渐变是没有加前缀的，可能会有兼容问题，其它的都是 unocss 实现，应该不会有问题

![image](https://github.com/Ares-Chang/wooden-fish/assets/36911513/9c5b71e6-b35d-4b1d-a3f3-7842612c33e1)

**Comment by Ares-Chang** [comment]
长期未响应关闭此 issues，如果有问题欢迎反馈
